"""The oracle. Projects every parity vector through the Python assessor.

    python3 parity/emit.py > parity/assess.golden.json

`src/aletheia/assess.py` is authoritative. Where the TypeScript port and this
file disagree, this file is right and the port is wrong — the same relationship
`cognitive/stratum` uses between its Python reference and its TS core, and for
the same reason: two peers can argue forever, an oracle cannot.

The projection is deliberately narrower than the full `Assessment`. It carries
the things that must be identical across implementations and omits the things
that legitimately differ:

  included   score, matched features per family, match ordering, the slice
             caps, governing parameters, the band boundaries, verification
             step count
  excluded   the *label* for a band (Python says severity low/moderate/high,
             the port still says recommendation proceed/verify/stop — issue #2)
             and the prose of `reasoning`, which is presentation

Band, not label, is the invariant. Naming is allowed to differ while the
thresholds are not.
"""
from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

from aletheia.assess import assess  # noqa: E402

VECTORS = pathlib.Path(__file__).resolve().parent / "vectors.jsonl"

# Python rounds the score to 4dp inside assess(); the port does not round at
# all. Comparing at 4dp is therefore comparing the oracle's own output, and a
# port that returns 0.8200000000000001 where the oracle says 0.82 is a real
# divergence, not a floating-point technicality to be papered over.
PRECISION = 4


def band(score: float) -> str:
    """The boundary, named neutrally so the two vocabularies can coexist."""
    if score < 0.3:
        return "low"
    if score < 0.6:
        return "mid"
    return "high"


def project_one(case: dict) -> dict:
    a = assess(case["content"], case["source"])
    return {
        "id": case["id"],
        "source": case["source"],
        "score": round(a.injection_risk_score, PRECISION),
        "band": band(a.injection_risk_score),
        "governing_parameters": a.governing_parameters,
        "factors": [
            {
                "category": f["category"],
                "weight": f["weight"],
                "matches": f["matches"],
            }
            for f in a.risk_factors
        ],
        "verification_step_count": len(a.verification_steps or []),
    }


def project() -> dict:
    cases = [
        json.loads(line)
        for line in VECTORS.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    return {
        "_note": (
            "Generated by parity/emit.py from parity/vectors.jsonl. Do not edit "
            "by hand — regenerate. CI regenerates and diffs, so a stale golden "
            "cannot hide drift."
        ),
        "_corpus": "vectors.jsonl",
        "precision": PRECISION,
        "vector_count": len(cases),
        "cases": [project_one(c) for c in cases],
    }


if __name__ == "__main__":
    # sort_keys so key ordering can never mask or introduce a diff.
    print(json.dumps(project(), indent=2, sort_keys=True, ensure_ascii=False))
