/**
 * The port's projection of the Unicode boundary mutation corpus.
 *
 *   npx tsx parity/emit_mutations.ts > /tmp/ts-mutations.json
 *   python3 parity/compare.py parity/mutations.golden.json /tmp/ts-mutations.json
 *
 * Reads the same generated corpus the oracle reads. As in emit.ts: no scoring
 * logic here, and nothing may normalise or special-case an output to make a
 * comparison pass — that would hide the divergence inside the harness.
 */

import { readFileSync } from "node:fs";
import { assess } from "../typescript/src/assess.js";
import type { ContentSource } from "../typescript/src/types.js";

const CORPUS = new URL("./mutations.jsonl", import.meta.url);
const PRECISION = 4;
const SOURCE = "web_search" as ContentSource;

function round(n: number, dp: number): number {
  return Number(n.toFixed(dp));
}

function band(score: number): string {
  if (score < 0.3) return "low";
  if (score < 0.6) return "mid";
  return "high";
}

interface MutationCase {
  id: string;
  seed: string;
  mutation: string;
  content: string;
}

const cases: MutationCase[] = readFileSync(CORPUS, "utf8")
  .split("\n")
  .filter((l) => l.trim().length > 0)
  .map((l) => JSON.parse(l) as MutationCase);

const projection = {
  _note:
    "Generated by parity/emit_mutations.py from parity/mutations.jsonl. " +
    "Do not edit by hand — regenerate. CI regenerates and diffs.",
  _corpus: "mutations.jsonl",
  precision: PRECISION,
  vector_count: cases.length,
  cases: cases.map((c) => {
    const a = assess({ content: c.content, source: SOURCE });
    return {
      id: c.id,
      source: SOURCE,
      score: round(a.injectionRiskScore, PRECISION),
      band: band(a.injectionRiskScore),
      governing_parameters: a.governingParameters,
      factors: a.riskFactors.map((f) => ({
        category: f.category,
        weight: f.weight,
        matches: f.matches,
      })),
      verification_step_count: (a.verificationSteps ?? []).length,
    };
  }),
};

function canonical(x: unknown): unknown {
  if (Array.isArray(x)) return x.map(canonical);
  if (typeof x === "object" && x !== null) {
    return Object.fromEntries(
      Object.entries(x as Record<string, unknown>)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([k, v]) => [k, canonical(v)]),
    );
  }
  return x;
}

process.stdout.write(JSON.stringify(canonical(projection), null, 2) + "\n");
