/**
 * The port's answer to the same questions. Emits the identical projection
 * shape as parity/emit.py so the two can be compared field by field.
 *
 *   npx tsx parity/emit.ts > /tmp/ts.json
 *   python3 parity/compare.py parity/assess.golden.json /tmp/ts.json
 *
 * This file must never contain scoring logic. It reads vectors and calls
 * `assess` — if it ever starts adjusting, normalising or special-casing an
 * output to make a comparison pass, the harness has been defeated and the
 * divergence it exists to surface is now hidden inside the harness itself.
 */

import { readFileSync } from "node:fs";
import { assess } from "../typescript/src/assess.js";
import type { ContentSource } from "../typescript/src/types.js";

const VECTORS = new URL("./vectors.jsonl", import.meta.url);

// Mirrors PRECISION in parity/emit.py. The Python oracle rounds to 4dp inside
// assess(); this port does not round at all, so the rounding is applied here
// at the projection boundary rather than silently tolerated by the comparator.
const PRECISION = 4;

function round(n: number, dp: number): number {
  return Number(n.toFixed(dp));
}

function band(score: number): string {
  if (score < 0.3) return "low";
  if (score < 0.6) return "mid";
  return "high";
}

interface Vector {
  id: string;
  source: string;
  content: string;
}

const cases: Vector[] = readFileSync(VECTORS, "utf8")
  .split("\n")
  .filter((l) => l.trim().length > 0)
  .map((l) => JSON.parse(l) as Vector);

const projection = {
  _note:
    "Generated by parity/emit.py from parity/vectors.jsonl. Do not edit " +
    "by hand — regenerate. CI regenerates and diffs, so a stale golden " +
    "cannot hide drift.",
  precision: PRECISION,
  vector_count: cases.length,
  cases: cases.map((c) => {
    const a = assess({
      content: c.content,
      source: c.source as ContentSource,
    });
    return {
      id: c.id,
      source: c.source,
      score: round(a.injectionRiskScore, PRECISION),
      band: band(a.injectionRiskScore),
      governing_parameters: a.governingParameters,
      factors: a.riskFactors.map((f) => ({
        category: f.category,
        weight: f.weight,
        matches: f.matches,
      })),
      verification_step_count: (a.verificationSteps ?? []).length,
    };
  }),
};

/** Recursively sort keys so key order can never mask or introduce a diff. */
function canonical(x: unknown): unknown {
  if (Array.isArray(x)) return x.map(canonical);
  if (typeof x === "object" && x !== null) {
    return Object.fromEntries(
      Object.entries(x as Record<string, unknown>)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([k, v]) => [k, canonical(v)]),
    );
  }
  return x;
}

process.stdout.write(JSON.stringify(canonical(projection), null, 2) + "\n");
