"""The oracle's projection of the Unicode boundary mutation corpus.

    python3 parity/emit_mutations.py > parity/mutations.golden.json

Same projection shape and same oracle rule as `emit.py`; a second corpus rather
than a second mechanism. It is kept separate from `vectors.jsonl` because the
two answer different questions and mixing them would bury one in the other:

    vectors.jsonl    one case per mirrored joint — does the port agree about
                     weights, thresholds, caps, ordering?
    mutations.jsonl  every detection atom, decorated at both boundaries with
                     every edge character — can Unicode change the answer?

651 cases, all generated. Regenerate with:

    cd parity && PYTHONPATH=. python3 unicode_boundary_mutations.py > mutations.jsonl
"""
from __future__ import annotations

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))
sys.path.insert(0, str(HERE))

from emit import PRECISION, band, project_one  # noqa: E402

CORPUS = HERE / "mutations.jsonl"

# The mutation corpus carries no per-case source; the threat model this exists
# to defend is untrusted inbound content, so every case is scored as one.
SOURCE = "web_search"


def project() -> dict:
    cases = [
        json.loads(line)
        for line in CORPUS.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    return {
        "_note": (
            "Generated by parity/emit_mutations.py from parity/mutations.jsonl. "
            "Do not edit by hand — regenerate. CI regenerates and diffs."
        ),
        "_corpus": "mutations.jsonl",
        "precision": PRECISION,
        "vector_count": len(cases),
        "cases": [
            project_one({"id": c["id"], "source": SOURCE, "content": c["content"]})
            for c in cases
        ],
    }


if __name__ == "__main__":
    print(json.dumps(project(), indent=2, sort_keys=True, ensure_ascii=False))
